---
datacenter:
  children:
    routers:
      hosts:
          192.168.0.[1:6]
      vars:
        testVar: 999
    switches:
       hosts:
         192.168.0.6
  vars:
     ansible_connection: network_cli
     ansible_network_os: ios
     ansible_user: admin
     ansible_ssh_pass: cisco
     ntp_servers:
